---
color_dark_brown:
  r: 30
  g: 25
  b: 15
  a: 255
color_medium_brown:
  r: 110
  g: 90
  b: 80
  a: 255
color_light_green:
  r: 110
  g: 180
  b: 32
  a: 255
color_tile_blue_light:
  r: 4
  g: 30
  b: 50
  a: 255
color_tile_blue_dark:
  r: 2
  g: 17
  b: 35
  a: 255
color_light_brown:
  r: 158
  g: 134
  b: 100
  a: 255
color_ice_blue:
  r: 0
  g: 128
  b: 255
  a: 255
color_dark_blue:
  r: 0
  g: 0
  b: 64
  a: 255
color_very_dark_blue:
  r: 1
  g: 10
  b: 18
  a: 255
color_orange:
  r: 217
  g: 54
  b: 0
  a: 255
color_red:
  r: 102
  g: 0
  b: 0
  a: 255
color_medium_grey:
  r: 40
  g: 40
  b: 40
  a: 255
color_mint_green:
  r: 146
  g: 197
  b: 127
  a: 255
color_blueish_grey:
  r: 45
  g: 45
  b: 65
  a: 255
color_pink:
  r: 210
  g: 137
  b: 154
  a: 255
color_rose_red:
  r: 104
  g: 43
  b: 58
  a: 255
color_light_orange:
  r: 246
  g: 148
  b: 12
  a: 255
color_bone_white:
  r: 24
  g: 226
  b: 183
  a: 255
color_warm_grey:
  r: 99
  g: 95
  b: 82
  a: 255
color_soft_green:
  r: 172
  g: 216
  b: 172
  a: 255
color_light_grey:
  r: 132
  g: 132
  b: 132
  a: 255
color_console:
  r: 0x76
  g: 0x30
  b: 0
  a: 200
load_map_file_every_frame: false
tile_noise_scaler: 4.0
highlight_player_move: 226
highlight_alpha_attack: 25
sound_alpha: 86
grid_alpha: 8
grid_alpha_visible: 80
grid_alpha_overlay: 150
## Valid values for map_load
# FromFile(filename): load from map.xp file
# FromVaultFile(filename): load a given vault as the level
# TestWall: test map for checking wall interactions
# TestRandom: test random generation
# TestMap: test map for unit tests
# Random: generated map, not currently working
# Empty: empty map, used in unit tests 
# TestCorner: test map with corners of different types
# TestPlayer: test map for player interactions
# ProcGen: procedurally generated map, given a filename in resources/procgen
map_load: #TestVaults
    ProcGen: "map1.yaml"
#VaultFile: "vaults/Vaults - Vault25.csv"
#FromFile: "maps.txt"
map_file: map.xp
idle_speed: 5
draw_mouse_line: false
draw_star_path: false
frame_rate: 25
item_throw_speed: 30.0
key_speed: 5.0
player_attack_speed: 2.0
player_attack_hammer_speed: 1.0
player_vault_sprite_speed: 2.0
player_vault_move_speed: 2.0
sound_timeout: 0.5
yell_radius: 4
swap_radius: 4
fog_of_war: true
player_health: 3
explored_alpha: 150
sound_rubble_radius: 1
sound_grass_radius: 1
sound_radius_crushed: 3
sound_radius_attack: 3
sound_radius_trap: 3
sound_radius_monster: 3
sound_radius_stone: 3
sound_radius_player: 3
sound_radius_hammer: 3
freeze_trap_radius: 3
push_stun_turns: 3
overlay_directions: false
overlay_player_fov: false
overlay_fov_alg: false
overlay_floodfill: false
fov_radius_monster: 4
fov_radius_player: 4
console_max_height: 400
console_speed: 1.0
sound_radius_sneak: 1
sound_radius_walk: 2
sound_radius_run: 3
dampen_blocked_tile: 3
dampen_short_wall: 1
dampen_tall_wall: 2
take_screenshot: false
show_info: true
use_cursor: true

# delay before a key is repeated (seconds)
repeat_delay: 0.5

# whether to write out a map distribution file
write_map_distribution: true
